---

  - name: create a temp dir
    file:
      path={{tmp_dir}}
      state=directory

  - name: upload the WAR
    copy:
      src=application/{{app_name}}/{{app_version}}/{{war_name}}/{{ war_file }}
      dest={{tmp_dir}}/{{ war_file }}

  - name: compute the MD5 of the new WAR
    stat:
      path={{tmp_dir}}/{{ war_file }}
      get_md5=True
    register: tmp_war_stat
    changed_when: False

  - name: compute the MD5 of the existing WAR
    stat:
      path={{tomcat_web_apps_dir}}/{{ war_name }}.war
      get_md5=True
    register: app_war_stat
    changed_when: False

  #- debug: var=tmp_war_stat.stat.md5
  #- debug: var=app_war_stat.stat.md5

  - name: copy the WAR
    shell: cp {{tmp_dir}}/{{ war_file }} {{tomcat_web_apps_dir}}/{{ war_name }}.war
    when: not app_war_stat.stat.md5 is defined or not tmp_war_stat.stat.md5 == app_war_stat.stat.md5
    notify: restart tomcat

  - name: chown the WAR
    file:
      name={{tomcat_web_apps_dir}}/{{ war_name }}.war
      owner={{tomcat_user}}
      group={{tomcat_group}}

  - name: cleanup temporary directory
    file:
      path={{tmp_dir}}
      state=absent

